### PR TITLE
Readme

### LINKED ISSUE #127: CLEANUP: README

### PR DESCRIPTION
**Pull request by jake-shasteen**
Resolves #127

### CODE REVIEW

**Comment by asu91** [comment]
@jake-shasteen reviewed. It might need iterations on it in the future for the final copy

**Comment by jake-shasteen** [comment]
When you say iterations in the future, are you looking for more content -- and if so what kind of content -- or on refinement for what is already there?

**Comment by asu91** [comment]
@jake-shasteen There might be little tweaks here and there that might come in the next few days. The current content is fine though!

**Comment by bignell** [comment]
@tiffeli Love the component hierarchy.

**Pull request merged**
